"""empty message

Revision ID: 10f770e1afc3
Revises:
Create Date: 2025-08-13 16:08:41.602323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "10f770e1afc3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("cutoff_date", sa.DateTime(), nullable=True),
        sa.Column(
            "page_tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_table(
        "thread",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("history_id", sa.String(length=10), nullable=False),
        sa.Column("org_id", sa.String(length=256), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("last_sync", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("org_id", sa.String(length=256), nullable=False),
        sa.Column("thread_id", sa.String(length=16), nullable=False),
        sa.Column("history_id", sa.String(length=10), nullable=False),
        sa.Column("label_ids", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("internal_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("sender", sa.String(length=254), nullable=False),
        sa.Column("receiver", postgresql.ARRAY(sa.String(length=254)), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "embeeding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.Column("parent_message_id", sa.String(length=16), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.email"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_table("thread")
    op.drop_table("org")
    # ### end Alembic commands ###
